# A company started to invest in digital marketing as a new way of their product promotions. For that they collected data and decided to carry out a study on it.

## a● The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.


## b● The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
dataset=pd.read_csv("Sales_add.csv")
import pandas as pd
from scipy import stats
from statsmodels.stats import weightstats as stests

In [80]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


In [81]:
dataset.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

# a● *The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.*

### Null Hypothesis(Ho):Sales did not improved after promotions via digital marketing was introduced

### Alternate Hypothesis(Ha):avg sales has increased after promotions via digital marketing was introduced

### let the significance level be 5%

## Since the sales after and before digital promo is dependent, number of samples<30; we use paired t- test

In [82]:
from statsmodels.stats import weightstats as stests
ttest,pval = stats.ttest_rel(dataset['Sales_before_digital_add(in $)'], dataset['Sales_After_digital_add(in $)'])
print(pval)
if pval>0.05:
    print("We accept null hypothesis; sales did not improve after digital promos")
else:
    print("We reject null hypothesis; sales improved after the introduction of digital promos and mean sales improved")

6.336667004575778e-11
We reject null hypothesis; sales improved after the introduction of digital promos and mean sales improved


### this can also be identified from the average sales data of before and after the digital promos; by computing statistical features using describe function

In [83]:
before_digital=dataset["Sales_before_digital_add(in $)"]
After_digital=dataset["Sales_After_digital_add(in $)"]


In [84]:
b=before_digital.describe()
b=pd.DataFrame(b)
a=After_digital.describe()
a=pd.DataFrame(a)
extracted_col = a["Sales_After_digital_add(in $)"]
b=b.join(extracted_col)
b[1:2]

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
mean                   149239.954545                  231123.727273

## <u>Observation</u>:

### The avg sales has increased after promotions via digital marketing was introduced from the above set of results and also via Hypothesis testing(paired t test)

# b● *The company needs to check whether there is any dependency between the features “Region” and “Manager”*

#### Null Hypothesis(Ho): There is no dependency between the features "Region" and "Manager"

#### Alternate Hypothesis(Ha):There is a dependency between the features "Region" and "Manager"

#### Let the significance level be 5%

### Since the problem here is to check the dependancy between two categorical variable; chi-square test can be used:

In [85]:
dataset['Region'].value_counts()

Region - A    10
Region - B     7
Region - C     5
Name: Region, dtype: int64

In [86]:
dataset['Manager'].value_counts()

Manager - A    9
Manager - B    7
Manager - C    6
Name: Manager, dtype: int64

In [87]:
dataset.columns

Index(['Month', 'Region', 'Manager', 'Sales_before_digital_add(in $)',
       'Sales_After_digital_add(in $)'],
      dtype='object')

In [88]:
contingency_table=pd.crosstab(dataset["Region"],dataset["Manager"])
print('contingency_table :-\n',contingency_table)

contingency_table :-
 Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


### Or the contingency table can also be calculated as:

In [89]:
ct = pd.crosstab(dataset.Region, dataset.Manager, margins=True)
ct

Manager     Manager - A  Manager - B  Manager - C  All
Region                                                
Region - A            4            3            3   10
Region - B            4            1            2    7
Region - C            1            3            1    5
All                   9            7            6   22

In [90]:
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)


Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [91]:
#Expected Values
e_1=stats.chi2_contingency(contingency_table)
Expected_Values = e_1[3]
print("Expected Values :-\n",Expected_Values)

Expected Values :-
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]


In [92]:
no_of_rows=len(contingency_table.iloc[0:3,0])
no_of_columns=len(contingency_table.iloc[0,0:3])
df11=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",df11)
alpha = 0.05

Degree of Freedom:- 4


In [93]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 2.921995464852608


In [94]:
critical_value=chi2.ppf(q=1-alpha,df=df11)
print('critical_value:',critical_value)

critical_value: 9.487729036781154


In [95]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=df11)
print('p-value:',p_value)

p-value: 0.5709629929220089


In [96]:
print('Significance level: ',alpha)
print('Degree of Freedom: ',df11)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)

Significance level:  0.05
Degree of Freedom:  4
chi-square statistic: 2.921995464852608
critical_value: 9.487729036781154
p-value: 0.5709629929220089


In [97]:
if chi_square_statistic>=critical_value:
    print("Reject Ho,There is a relationship between 2 categorical variables")
else:
    print("Retain Ho,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject Ho,There is a relationship between 2 categorical variables")
else:
    print("Retain Ho,There is no relationship between 2 categorical variables")

Retain Ho,There is no relationship between 2 categorical variables
Retain Ho,There is no relationship between 2 categorical variables


# <u>Observation</u>:

## Since the p-value is high(greater than the significance level) & critical value computed is greater than test statistics value; *We can conclude that Regions and Managers are independent ; no relationship exist between these two features*